modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Cycle%20Title%20Screen%20Splash"
logoFile="icon.png"

[[mods]]
modId="cycletitlescreensplash"
version="1.1"
displayName="Cycle Title Screen Splash"
displayURL="https://serilum.com/mod/cycle-title-screen-splash"
authors="Rick South"
description='''The splash text on the main menu will keep changing after a configurable delay.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.cycletitlescreensplash]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cycletitlescreensplash]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "cycletitlescreensplash_neoforge.mixins.json"